apiVersion: v1
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
items:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: mockserver
    name: mockserver
  spec:
    ports:
    - name: 1080-tcp
      port: 1080
      protocol: TCP
      targetPort: 1080
    selector:
      deployment: mockserver
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      app: mockserver
    name: mockserver
  spec:
    replicas: 1
    selector:
      matchLabels:
        deployment: mockserver
    template:
      metadata:
        labels:
          deployment: mockserver
      spec:
        containers:
        - image: quay.io/mganisin/mockserver:latest
          name: mockserver
          ports:
          - containerPort: 1080
            protocol: TCP
          lifecycle:
            postStart:
              exec:
                command: ["/bin/sh", "init-mockserver"]
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    labels:
      app: mockserver
    name: mockserver
  spec:
    port:
      targetPort: 1080-tcp
    tls:
      insecureEdgeTerminationPolicy: Allow
      termination: edge
    to:
      kind: Service
      name: mockserver
      weight: 100
    wildcardPolicy: None
