#!/bin/sh

while ! curl -f -v -X PUT "http://localhost:1080/mockserver/expectation" -d '{
	"httpRequest" : {"headers": {"Host": ["mockserver.*"]}},
	"httpResponseTemplate": {
		"templateType": "JAVASCRIPT",
		"template": "return {
			statusCode: 200,
			cookies: {session: request.headers[\"Session-Id\"] && request.headers[\"Session-Id\"][0]},
			headers: {Date: [Date()]},
			body: JSON.stringify(request)};"},
	"priority": -100}' ; do
	sleep 1
done

curl -f -v -X PUT "http://localhost:1080/mockserver/expectation" -d '{
	"httpRequest" : {"path": "/bytes/.*"},
	"httpResponseTemplate": {
		"templateType": "JAVASCRIPT",
		"template": "return {
			statusCode: 200,
			cookies: {session: request.headers[\"Session-Id\"] && request.headers[\"Session-Id\"][0]},
			headers: {Date: [Date()]},
			body: \"#\".repeat(parseInt(request.path.split(\"/\")[2]))};"}}'

curl -f -v -X PUT "http://localhost:1080/mockserver/expectation" -d '{
	"httpRequest" : {"path": "/delay/.*"},
	"httpResponseTemplate": {
		"templateType": "JAVASCRIPT",
		"template": "return {
			delay: {timeUnit: \"SECONDS\", value: parseInt(request.path.split(\"/\")[2])},
			statusCode: 200,
			cookies: {session: request.headers[\"Session-Id\"] && request.headers[\"Session-Id\"][0]},
			headers: {Date: [Date()]},
			body: JSON.stringify(request)};"}}'

curl -f -v -X PUT "http://localhost:1080/mockserver/expectation" -d '{
	"httpRequest" : {"path": "/ip"},
	"httpResponseTemplate": {
		"templateType": "JAVASCRIPT",
		"template": "return {
			statusCode: 200,
			cookies: {session: request.headers[\"Session-Id\"] && request.headers[\"Session-Id\"][0]},
			headers: {Date: [Date()]},
			body: JSON.stringify({origin: request.headers.forwarded[0].split(\";\")[0].split(\"=\")[1]})};"}}'

curl -f -v -X PUT "http://localhost:1080/mockserver/expectation" -d '{
	"httpRequest" : {"path": "/redirect-to"},
	"httpResponseTemplate": {
		"templateType": "JAVASCRIPT",
		"template": "return {
			statusCode: 302,
			cookies: {session: request.headers[\"Session-Id\"] && request.headers[\"Session-Id\"][0]},
			headers: {Location: request.queryStringParameters[\"url\"]}};"}}'

curl -f -v -X PUT "http://localhost:1080/mockserver/expectation" -d '{
	"httpRequest" : {"path": "/response-headers"},
	"httpResponseTemplate": {
		"templateType": "JAVASCRIPT",
		"template": "return {
			statusCode: 200,
			cookies: {session: request.headers[\"Session-Id\"] && request.headers[\"Session-Id\"][0]},
			headers: request.queryStringParameters,
			body: JSON.stringify(request)};"}}'

curl -f -v -X PUT "http://localhost:1080/mockserver/expectation" -d '{
	"httpRequest" : {"path": "/status/.*"},
	"httpResponseTemplate": {
		"templateType": "JAVASCRIPT",
		"template": "return {
			statusCode: parseInt(request.path.split(\"/\")[2]),
			cookies: {session: request.headers[\"Session-Id\"] && request.headers[\"Session-Id\"][0]},
			headers: {Date: [Date()]},
			body: JSON.stringify(request)};"}}'
