#!/bin/sh

while ! curl -f -v -X PUT "http://localhost:1080/mockserver/expectation" -d '{"httpRequest" : {"headers": {"Host": ["mockserver.*"]}}, "httpResponseTemplate": {"templateType": "JAVASCRIPT", "template": "return {statusCode: 200, cookies: {session: request.headers[\"Session-Id\"] && request.headers[\"Session-Id\"][0]}, headers: {Date: [Date()]}, body: JSON.stringify(request)};"}, "priority": -100}' ; do
	sleep 1
done
